// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_weather3;
lv_obj_t *uic_weather2;
lv_obj_t *uic_weather1;
lv_obj_t *uic_humidity;
lv_obj_t *uic_temperature;
lv_obj_t *uic_time;
lv_obj_t *uic_lastupdated;
lv_obj_t *uic_ipaddress;
lv_obj_t *uic_Screen1;
lv_obj_t *ui_screen1 = NULL;lv_obj_t *ui_container2 = NULL;lv_obj_t *ui_container3 = NULL;lv_obj_t *ui_ipaddress = NULL;lv_obj_t *ui_lastupdated = NULL;lv_obj_t *ui_container9 = NULL;lv_obj_t *ui_time = NULL;lv_obj_t *ui_container4 = NULL;lv_obj_t *ui_container10 = NULL;lv_obj_t *ui_temperature = NULL;lv_obj_t *ui_container11 = NULL;lv_obj_t *ui_humidity = NULL;lv_obj_t *ui_container5 = NULL;lv_obj_t *ui_container6 = NULL;lv_obj_t *ui_weather1 = NULL;lv_obj_t *ui_container7 = NULL;lv_obj_t *ui_weather2 = NULL;lv_obj_t *ui_container8 = NULL;lv_obj_t *ui_weather3 = NULL;
// event funtions

// build funtions

void ui_screen1_screen_init(void)
{
ui_screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_screen1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_flex_flow(ui_screen1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_screen1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

ui_container2 = lv_obj_create(ui_screen1);
lv_obj_remove_style_all(ui_container2);
lv_obj_set_width( ui_container2, 480);
lv_obj_set_height( ui_container2, 800);
lv_obj_set_flex_flow(ui_container2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_image_src( ui_container2, &ui_img_images_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_width(ui_container2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_container3 = lv_obj_create(ui_container2);
lv_obj_remove_style_all(ui_container3);
lv_obj_set_height( ui_container3, 36);
lv_obj_set_width( ui_container3, lv_pct(100));
lv_obj_remove_flag( ui_container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_container3, lv_color_hex(0xFFEC00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_container3, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_container3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_container3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_container3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_container3, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_container3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_container3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_container3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_container3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ipaddress = lv_label_create(ui_container3);
lv_obj_set_width( ui_ipaddress, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ipaddress, LV_SIZE_CONTENT);   /// 90
lv_obj_set_align( ui_ipaddress, LV_ALIGN_CENTER );
lv_label_set_text(ui_ipaddress,"192.168.0.120");
lv_obj_set_style_text_color(ui_ipaddress, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ipaddress, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_ipaddress, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ipaddress, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lastupdated = lv_label_create(ui_container3);
lv_obj_set_width( ui_lastupdated, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lastupdated, LV_SIZE_CONTENT);   /// 90
lv_obj_set_align( ui_lastupdated, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_lastupdated,"10 mins ago");
lv_obj_set_style_text_color(ui_lastupdated, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lastupdated, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_lastupdated, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lastupdated, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_container9 = lv_obj_create(ui_container2);
lv_obj_remove_style_all(ui_container9);
lv_obj_set_height( ui_container9, 300);
lv_obj_set_width( ui_container9, lv_pct(100));
lv_obj_set_align( ui_container9, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_container9,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_container9, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_time = lv_label_create(ui_container9);
lv_obj_set_width( ui_time, lv_pct(100));
lv_obj_set_height( ui_time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_time, LV_ALIGN_CENTER );
lv_label_set_text(ui_time,"10:30");
lv_obj_set_style_text_color(ui_time, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_time, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_time, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_time, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_time, &ui_font_FontRobotoBold120, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_container4 = lv_obj_create(ui_container2);
lv_obj_remove_style_all(ui_container4);
lv_obj_set_height( ui_container4, 200);
lv_obj_set_width( ui_container4, lv_pct(100));
lv_obj_set_align( ui_container4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_container4,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_container4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_container10 = lv_obj_create(ui_container4);
lv_obj_remove_style_all(ui_container10);
lv_obj_set_width( ui_container10, lv_pct(50));
lv_obj_set_height( ui_container10, lv_pct(100));
lv_obj_set_align( ui_container10, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_container10,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_container10, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_temperature = lv_label_create(ui_container10);
lv_obj_set_width( ui_temperature, lv_pct(100));
lv_obj_set_height( ui_temperature, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_temperature, LV_ALIGN_CENTER );
lv_label_set_text(ui_temperature,"67.2");
lv_obj_set_style_text_color(ui_temperature, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_temperature, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_temperature, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_temperature, &ui_font_FontRoboto80, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_temperature, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_temperature, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_temperature, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_temperature, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_container11 = lv_obj_create(ui_container4);
lv_obj_remove_style_all(ui_container11);
lv_obj_set_width( ui_container11, lv_pct(50));
lv_obj_set_height( ui_container11, lv_pct(100));
lv_obj_set_align( ui_container11, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_container11, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_humidity = lv_label_create(ui_container11);
lv_obj_set_width( ui_humidity, lv_pct(100));
lv_obj_set_height( ui_humidity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_humidity, LV_ALIGN_CENTER );
lv_label_set_text(ui_humidity,"52.3");
lv_obj_set_style_text_color(ui_humidity, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_humidity, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_humidity, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_humidity, &ui_font_FontRoboto80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_container5 = lv_obj_create(ui_container2);
lv_obj_remove_style_all(ui_container5);
lv_obj_set_width( ui_container5, lv_pct(100));
lv_obj_set_flex_grow( ui_container5, 1);
lv_obj_set_align( ui_container5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_container5,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_container5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_container6 = lv_obj_create(ui_container5);
lv_obj_remove_style_all(ui_container6);
lv_obj_set_width( ui_container6, lv_pct(34));
lv_obj_set_height( ui_container6, lv_pct(100));
lv_obj_set_align( ui_container6, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_weather1 = lv_image_create(ui_container6);
lv_obj_set_width( ui_weather1, lv_pct(100));
lv_obj_set_height( ui_weather1, lv_pct(100));
lv_obj_set_align( ui_weather1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_weather1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_weather1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_container7 = lv_obj_create(ui_container5);
lv_obj_remove_style_all(ui_container7);
lv_obj_set_width( ui_container7, lv_pct(34));
lv_obj_set_height( ui_container7, lv_pct(100));
lv_obj_set_align( ui_container7, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_weather2 = lv_image_create(ui_container7);
lv_obj_set_width( ui_weather2, lv_pct(100));
lv_obj_set_height( ui_weather2, lv_pct(100));
lv_obj_set_align( ui_weather2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_weather2, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_weather2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_container8 = lv_obj_create(ui_container5);
lv_obj_remove_style_all(ui_container8);
lv_obj_set_height( ui_container8, lv_pct(100));
lv_obj_set_flex_grow( ui_container8, 1);
lv_obj_set_align( ui_container8, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_weather3 = lv_image_create(ui_container8);
lv_obj_set_width( ui_weather3, lv_pct(100));
lv_obj_set_height( ui_weather3, lv_pct(100));
lv_obj_set_align( ui_weather3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_weather3, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_weather3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_Screen1 = ui_screen1;
uic_ipaddress = ui_ipaddress;
uic_lastupdated = ui_lastupdated;
uic_time = ui_time;
uic_temperature = ui_temperature;
uic_humidity = ui_humidity;
uic_weather1 = ui_weather1;
uic_weather2 = ui_weather2;
uic_weather3 = ui_weather3;

}

void ui_screen1_screen_destroy(void)
{
   if (ui_screen1) lv_obj_del(ui_screen1);

// NULL screen variables
uic_Screen1= NULL;
ui_screen1= NULL;
ui_container2= NULL;
ui_container3= NULL;
uic_ipaddress= NULL;
ui_ipaddress= NULL;
uic_lastupdated= NULL;
ui_lastupdated= NULL;
ui_container9= NULL;
uic_time= NULL;
ui_time= NULL;
ui_container4= NULL;
ui_container10= NULL;
uic_temperature= NULL;
ui_temperature= NULL;
ui_container11= NULL;
uic_humidity= NULL;
ui_humidity= NULL;
ui_container5= NULL;
ui_container6= NULL;
uic_weather1= NULL;
ui_weather1= NULL;
ui_container7= NULL;
uic_weather2= NULL;
ui_weather2= NULL;
ui_container8= NULL;
uic_weather3= NULL;
ui_weather3= NULL;

}
