// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_date;
lv_obj_t *uic_ampm;
lv_obj_t *uic_time;
lv_obj_t *uic_lastupdated;
lv_obj_t *uic_ipaddress;
lv_obj_t *uic_containerbg;
lv_obj_t *uic_Screen1;
lv_obj_t *ui_screen1 = NULL;lv_obj_t *ui_containerbg = NULL;lv_obj_t *ui_container3 = NULL;lv_obj_t *ui_ipaddress = NULL;lv_obj_t *ui_lastupdated = NULL;lv_obj_t *ui_container9 = NULL;lv_obj_t *ui_container7 = NULL;lv_obj_t *ui_time = NULL;lv_obj_t *ui_ampm = NULL;lv_obj_t *ui_container8 = NULL;lv_obj_t *ui_container10 = NULL;lv_obj_t *ui_date = NULL;lv_obj_t *ui_container1 = NULL;lv_obj_t *ui_image1 = NULL;lv_obj_t *ui_label1 = NULL;lv_obj_t *ui_container2 = NULL;lv_obj_t *ui_container6 = NULL;lv_obj_t *ui_panel1 = NULL;lv_obj_t *ui_container4 = NULL;lv_obj_t *ui_panel2 = NULL;lv_obj_t *ui_container5 = NULL;
// event funtions

// build funtions

void ui_screen1_screen_init(void)
{
ui_screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_screen1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_flex_flow(ui_screen1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_screen1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_radius(ui_screen1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_containerbg = lv_obj_create(ui_screen1);
lv_obj_remove_style_all(ui_containerbg);
lv_obj_set_width( ui_containerbg, lv_pct(100));
lv_obj_set_height( ui_containerbg, lv_pct(100));
lv_obj_set_x( ui_containerbg, 10 );
lv_obj_set_y( ui_containerbg, -111 );
lv_obj_set_flex_flow(ui_containerbg,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_containerbg, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_containerbg, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_image_src( ui_containerbg, &ui_img_images_img_clear_day_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_width(ui_containerbg, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_container3 = lv_obj_create(ui_containerbg);
lv_obj_remove_style_all(ui_container3);
lv_obj_set_width( ui_container3, lv_pct(100));
lv_obj_set_height( ui_container3, LV_SIZE_CONTENT);   /// 30
lv_obj_remove_flag( ui_container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_container3, lv_color_hex(0xFFEC00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_container3, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_container3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_container3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_container3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_container3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ipaddress = lv_label_create(ui_container3);
lv_obj_set_width( ui_ipaddress, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ipaddress, LV_SIZE_CONTENT);   /// 90
lv_obj_set_align( ui_ipaddress, LV_ALIGN_CENTER );
lv_label_set_text(ui_ipaddress,"---");
lv_obj_set_style_text_color(ui_ipaddress, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ipaddress, 140, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_ipaddress, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ipaddress, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lastupdated = lv_label_create(ui_container3);
lv_obj_set_width( ui_lastupdated, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lastupdated, LV_SIZE_CONTENT);   /// 90
lv_obj_set_align( ui_lastupdated, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_lastupdated,"---");
lv_obj_set_style_text_color(ui_lastupdated, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lastupdated, 140, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_lastupdated, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lastupdated, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_container9 = lv_obj_create(ui_containerbg);
lv_obj_remove_style_all(ui_container9);
lv_obj_set_width( ui_container9, lv_pct(100));
lv_obj_set_height( ui_container9, LV_SIZE_CONTENT);   /// 200
lv_obj_set_align( ui_container9, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_container9,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_container9, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_container9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_container9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_container9, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_container9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_container7 = lv_obj_create(ui_container9);
lv_obj_remove_style_all(ui_container7);
lv_obj_set_width( ui_container7, 100);
lv_obj_set_height( ui_container7, 50);
lv_obj_set_align( ui_container7, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_time = lv_label_create(ui_container9);
lv_obj_set_width( ui_time, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_time, LV_ALIGN_CENTER );
lv_label_set_text(ui_time,"--:--");
lv_obj_set_style_text_color(ui_time, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_time, 140, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_time, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_time, &ui_font_fontinter120, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ampm = lv_label_create(ui_time);
lv_obj_set_width( ui_ampm, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ampm, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ampm, 0 );
lv_obj_set_y( ui_ampm, -9 );
lv_obj_set_align( ui_ampm, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_ampm,"--");
lv_obj_set_style_text_color(ui_ampm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ampm, 140, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ampm, &ui_font_fontinter30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_container8 = lv_obj_create(ui_container9);
lv_obj_remove_style_all(ui_container8);
lv_obj_set_width( ui_container8, 100);
lv_obj_set_height( ui_container8, 50);
lv_obj_set_align( ui_container8, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_container10 = lv_obj_create(ui_containerbg);
lv_obj_remove_style_all(ui_container10);
lv_obj_set_height( ui_container10, 50);
lv_obj_set_width( ui_container10, lv_pct(100));
lv_obj_set_align( ui_container10, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_date = lv_label_create(ui_container10);
lv_obj_set_width( ui_date, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_date, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_date, LV_ALIGN_CENTER );
lv_label_set_text(ui_date,"---");
lv_obj_set_style_text_color(ui_date, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_date, 140, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_date, &ui_font_fontinter30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_container1 = lv_obj_create(ui_containerbg);
lv_obj_remove_style_all(ui_container1);
lv_obj_set_width( ui_container1, lv_pct(100));
lv_obj_set_height( ui_container1, LV_SIZE_CONTENT);   /// 40
lv_obj_set_align( ui_container1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_container1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_image1 = lv_image_create(ui_container1);
lv_image_set_src(ui_image1, &ui_img_images_location_png);
lv_obj_set_height( ui_image1, 24);
lv_obj_set_width( ui_image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_image1, 326 );
lv_obj_set_y( ui_image1, 25 );
lv_obj_set_align( ui_image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_image1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_label1 = lv_label_create(ui_container1);
lv_obj_set_width( ui_label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_label1,"--------");
lv_obj_set_style_text_color(ui_label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_label1, 140, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_label1, &ui_font_fontinter20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_label1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_label1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_label1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_label1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_container2 = lv_obj_create(ui_containerbg);
lv_obj_remove_style_all(ui_container2);
lv_obj_set_width( ui_container2, lv_pct(100));
lv_obj_set_height( ui_container2, LV_SIZE_CONTENT);   /// 150
lv_obj_set_align( ui_container2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_container2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_container2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_container2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_container2, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_container2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_container6 = lv_obj_create(ui_container2);
lv_obj_remove_style_all(ui_container6);
lv_obj_set_width( ui_container6, 80);
lv_obj_set_height( ui_container6, 50);
lv_obj_set_align( ui_container6, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_panel1 = lv_obj_create(ui_container2);
lv_obj_set_height( ui_panel1, 120);
lv_obj_set_flex_grow( ui_panel1, 1);
lv_obj_set_x( ui_panel1, -238 );
lv_obj_set_y( ui_panel1, 119 );
lv_obj_set_align( ui_panel1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panel1, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panel1, lv_color_hex(0xFFAD03), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panel1, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_panel1, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_panel1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_panel1, lv_color_hex(0xFFAD03), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_panel1, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_panel1, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_container4 = lv_obj_create(ui_container2);
lv_obj_remove_style_all(ui_container4);
lv_obj_set_width( ui_container4, 80);
lv_obj_set_height( ui_container4, 50);
lv_obj_set_align( ui_container4, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_panel2 = lv_obj_create(ui_container2);
lv_obj_set_height( ui_panel2, 120);
lv_obj_set_flex_grow( ui_panel2, 1);
lv_obj_set_align( ui_panel2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panel2, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panel2, lv_color_hex(0x347FFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panel2, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_panel2, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_panel2, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_panel2, lv_color_hex(0x347FFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_panel2, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_panel2, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_container5 = lv_obj_create(ui_container2);
lv_obj_remove_style_all(ui_container5);
lv_obj_set_width( ui_container5, 80);
lv_obj_set_height( ui_container5, 50);
lv_obj_set_align( ui_container5, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_Screen1 = ui_screen1;
uic_containerbg = ui_containerbg;
uic_ipaddress = ui_ipaddress;
uic_lastupdated = ui_lastupdated;
uic_time = ui_time;
uic_ampm = ui_ampm;
uic_date = ui_date;

}

void ui_screen1_screen_destroy(void)
{
   if (ui_screen1) lv_obj_del(ui_screen1);

// NULL screen variables
uic_Screen1= NULL;
ui_screen1= NULL;
uic_containerbg= NULL;
ui_containerbg= NULL;
ui_container3= NULL;
uic_ipaddress= NULL;
ui_ipaddress= NULL;
uic_lastupdated= NULL;
ui_lastupdated= NULL;
ui_container9= NULL;
ui_container7= NULL;
uic_time= NULL;
ui_time= NULL;
uic_ampm= NULL;
ui_ampm= NULL;
ui_container8= NULL;
ui_container10= NULL;
uic_date= NULL;
ui_date= NULL;
ui_container1= NULL;
ui_image1= NULL;
ui_label1= NULL;
ui_container2= NULL;
ui_container6= NULL;
ui_panel1= NULL;
ui_container4= NULL;
ui_panel2= NULL;
ui_container5= NULL;

}
