// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen1
extern void ui_screen1_screen_init(void);
extern void ui_screen1_screen_destroy(void);
extern lv_obj_t *ui_screen1;
extern lv_obj_t *ui_containerbg;
extern lv_obj_t *ui_container3;
extern lv_obj_t *ui_ipaddress;
extern lv_obj_t *ui_lastupdated;
extern lv_obj_t *ui_container9;
extern lv_obj_t *ui_container7;
extern lv_obj_t *ui_time;
extern lv_obj_t *ui_ampm;
extern lv_obj_t *ui_container8;
extern lv_obj_t *ui_container10;
extern lv_obj_t *ui_date;
extern lv_obj_t *ui_container1;
extern lv_obj_t *ui_image1;
extern lv_obj_t *ui_label1;
extern lv_obj_t *ui_container2;
extern lv_obj_t *ui_container6;
extern lv_obj_t *ui_panel1;
extern lv_obj_t *ui_container4;
extern lv_obj_t *ui_panel2;
extern lv_obj_t *ui_container5;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Screen1;
extern lv_obj_t *uic_containerbg;
extern lv_obj_t *uic_ipaddress;
extern lv_obj_t *uic_lastupdated;
extern lv_obj_t *uic_time;
extern lv_obj_t *uic_ampm;
extern lv_obj_t *uic_date;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

